version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: ap-south-2
    CLUSTER_NAME: codepipeline-test
    SERVICE_NAME: todo-service
    IMAGE_REPO_NAME: three-tier
    CONTAINER_NAME: todo-container
    TASK_DEFINITION_FAMILY: todo-task
    LOAD_BALANCER_NAME: todo-alb
    TARGET_GROUP_NAME: todo-target-group
    VPC_ID: vpc-0c6f6b98b166bd404
    SUBNETS: "subnet-083add9d53a052016,subnet-06e08945044b325a5"
    SECURITY_GROUP: "sg-0c9e4f3c7a6be673e"
    CAPACITY_PROVIDER: test

phases:
  install:
    commands:
      - echo "🔧 Installing tools..."
      - yum install -y jq || echo "jq already installed"

  pre_build:
    commands:
      - echo "🔐 Authenticating with ECR..."
      - |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          REPOSITORY_URI=$ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
          IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
          IMAGE_URI=$REPOSITORY_URI:$IMAGE_TAG
          export REPOSITORY_URI IMAGE_TAG IMAGE_URI

      - echo "📦 Ensuring ECR repo exists..."
      - |
          if ! aws ecr describe-repositories --repository-names $IMAGE_REPO_NAME > /dev/null 2>&1; then
            aws ecr create-repository --repository-name $IMAGE_REPO_NAME
          fi

      - echo "🔐 Logging into ECR..."
      - aws ecr get-login-password | docker login --username AWS --password-stdin $REPOSITORY_URI

      - echo "🔍 Checking Target Group..."
      - |
          TG_ARN=$(aws elbv2 describe-target-groups \
            --names $TARGET_GROUP_NAME \
            --query 'TargetGroups[0].TargetGroupArn' \
            --output text 2>/dev/null)

          if [ -z "$TG_ARN" ] || [ "$TG_ARN" = "None" ]; then
            TG_ARN=$(aws elbv2 create-target-group \
              --name $TARGET_GROUP_NAME \
              --protocol HTTP \
              --port 80 \
              --vpc-id $VPC_ID \
              --target-type ip \
              --query 'TargetGroups[0].TargetGroupArn' \
              --output text)
          fi

          export TARGET_GROUP_ARN=$TG_ARN

      - echo "🌐 Checking Load Balancer..."
      - |
          LB_ARN=$(aws elbv2 describe-load-balancers \
            --names $LOAD_BALANCER_NAME \
            --query 'LoadBalancers[0].LoadBalancerArn' \
            --output text 2>/dev/null)

          if [ -z "$LB_ARN" ] || [ "$LB_ARN" = "None" ]; then
            LB_ARN=$(aws elbv2 create-load-balancer \
              --name $LOAD_BALANCER_NAME \
              --subnets $(echo $SUBNETS | tr "," " ") \
              --security-groups $SECURITY_GROUP \
              --scheme internet-facing \
              --type application \
              --ip-address-type ipv4 \
              --query 'LoadBalancers[0].LoadBalancerArn' \
              --output text)

            aws elbv2 wait load-balancer-available --load-balancer-arns $LB_ARN

            aws elbv2 create-listener \
              --load-balancer-arn $LB_ARN \
              --protocol HTTP \
              --port 80 \
              --default-actions Type=forward,TargetGroupArn=$TG_ARN
          fi

          export LOAD_BALANCER_ARN=$LB_ARN

  build:
    commands:
      - echo "🐳 Building Docker image..."
      - docker build -t $IMAGE_URI .
      - echo "📤 Pushing image to ECR..."
      - docker push $IMAGE_URI

  post_build:
    commands:
      - echo "📄 Rendering ECS task definition..."
      - sed "s|<IMAGE_URI>|$IMAGE_URI|g" taskdef.json > new-taskdef.json
      - jq . new-taskdef.json || { echo "❌ Invalid JSON in taskdef"; exit 1; }

      - echo "📦 Registering ECS task definition..."
      - |
          TASK_REVISION=$(aws ecs register-task-definition \
            --cli-input-json file://new-taskdef.json \
            --query 'taskDefinition.revision' --output text)
          echo "🆕 Task definition revision: $TASK_REVISION"

      - echo "🔍 Checking if ECS service exists..."
      - |
          SERVICE_STATUS=$(aws ecs describe-services \
            --cluster $CLUSTER_NAME \
            --services $SERVICE_NAME \
            --query 'services[0].status' --output text 2>/dev/null)

          if [ -z "$SERVICE_STATUS" ] || [ "$SERVICE_STATUS" = "None" ]; then
            SERVICE_STATUS="MISSING"
          fi

      - |
          if [ "$SERVICE_STATUS" = "ACTIVE" ]; then
            echo "🌀 Updating ECS service..."
            aws ecs update-service \
              --cluster $CLUSTER_NAME \
              --service $SERVICE_NAME \
              --task-definition $TASK_DEFINITION_FAMILY:$TASK_REVISION \
              --force-new-deployment \
              --load-balancers "targetGroupArn=$TARGET_GROUP_ARN,containerName=$CONTAINER_NAME,containerPort=80" \
              --capacity-provider-strategy "capacityProvider=$CAPACITY_PROVIDER,weight=1" \
              --network-configuration "awsvpcConfiguration={subnets=[$SUBNETS],securityGroups=[$SECURITY_GROUP]}"
          else
            echo "🚀 Creating ECS service..."
            aws ecs create-service \
              --cluster $CLUSTER_NAME \
              --service-name $SERVICE_NAME \
              --task-definition $TASK_DEFINITION_FAMILY:$TASK_REVISION \
              --desired-count 1 \
              --load-balancers "targetGroupArn=$TARGET_GROUP_ARN,containerName=$CONTAINER_NAME,containerPort=80" \
              --capacity-provider-strategy "capacityProvider=$CAPACITY_PROVIDER,weight=1" \
              --network-configuration "awsvpcConfiguration={subnets=[$SUBNETS],securityGroups=[$SECURITY_GROUP]}"
          fi

      - echo "🌍 App should be live at:"
      - |
          aws elbv2 describe-load-balancers \
            --names $LOAD_BALANCER_NAME \
            --query 'LoadBalancers[0].DNSName' \
            --output text

artifacts:
  files:
    - new-taskdef.json
