version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: ap-south-2
    CLUSTER_NAME: codepipeline-test
    SERVICE_NAME: todo-service
    IMAGE_REPO_NAME: todo-app-repo
    CONTAINER_NAME: todo-container
    TASK_DEFINITION_FAMILY: todo-task
    SUBNETS: "subnet-083add9d53a052016"        # 🔁 Your public subnets
    SECURITY_GROUP: "sg-0c9e4f3c7a6be673e"         # 🔐 Your SG allowing port 80

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo Installing jq...
      - apt-get update && apt-get install -y jq

  pre_build:
    commands:
      - echo Logging into ECR...
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REPOSITORY_URI=$ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_URI=$REPOSITORY_URI:$IMAGE_TAG
      - echo $REPOSITORY_URI
      - |
        if ! aws ecr describe-repositories --repository-names $IMAGE_REPO_NAME >/dev/null 2>&1; then
          echo "Creating ECR repo..."
          aws ecr create-repository --repository-name $IMAGE_REPO_NAME
        fi
      - aws ecr get-login-password | docker login --username AWS --password-stdin $REPOSITORY_URI

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $IMAGE_URI .
      - echo Pushing Docker image...
      - docker push $IMAGE_URI

  post_build:
    commands:
      - echo Injecting image URI into task definition...
      - sed "s|<IMAGE_URI>|$IMAGE_URI|g" taskdef.json > new-taskdef.json

      - echo Registering task definition...
      - TASK_REVISION=$(aws ecs register-task-definition \
          --cli-input-json file://new-taskdef.json \
          --query 'taskDefinition.revision' --output text)

      - echo Checking if ECS service exists...
      - |
        SERVICE_EXISTS=$(aws ecs describe-services \
          --cluster $CLUSTER_NAME \
          --services $SERVICE_NAME \
          --query "services[0].status" --output text || echo "MISSING")

      - |
        if [ "$SERVICE_EXISTS" = "ACTIVE" ]; then
          echo "Updating ECS service to revision $TASK_REVISION"
          aws ecs update-service \
            --cluster $CLUSTER_NAME \
            --service $SERVICE_NAME \
            --task-definition $TASK_DEFINITION_FAMILY:$TASK_REVISION \
            --force-new-deployment
        else
          echo "Creating ECS service..."
          aws ecs create-service \
            --cluster $CLUSTER_NAME \
            --service-name $SERVICE_NAME \
            --task-definition $TASK_DEFINITION_FAMILY:$TASK_REVISION \
            --desired-count 1 \
            --launch-type FARGATE \
            --network-configuration "awsvpcConfiguration={subnets=[$SUBNETS],securityGroups=[$SECURITY_GROUP],assignPublicIp=ENABLED}"
        fi

artifacts:
  files:
    - new-taskdef.json
